export const futureGames = [
    {
        date: '13.10.2019',
        games: [
            {
                id: 1,
                home_team: 'Basketball USK Praha',
                visitor_team: 'BC Sparta Praha',
                place: 'Pod juliskou 4',
                time: '10:30',
                description: 'Jedná se o mimořádný zápas mezi USK Praha a BC Spart. Potřebujeme uklízeče a 4 výčepní.',
                salary: 100,
                organizer: 'BC Sparta Praha',
                img: '/u183.png',
                freePosts: [
                    'Uklízeč',
                    'Výčepní',
                ],
                positions : {
                    available: ['uklízeč', 'zapisovatel'],
                    unavailable: ['časoměřič', '24 sekund'],
                },
                sport: 'basketball',
                image: 'http://mba.org.mt/wp-content/uploads/2015/12/basketball-wallpaper-1280x768-1180x768.jpg',
            },
            {
                id: 9,
                home_team: 'Sparta Praha',
                visitor_team: 'SK Slavia Praha',
                place: 'Stadion Letná',
                time: '18:00',
                salary: 200,
                positions : {
                    available: ['uklízeč', 'podavač míčů'],
                    unavailable: ['kontrola lístků', 'výčepní'],
                },
                sport: 'football',
                image: 'https://akm-img-a-in.tosshub.com/indiatoday/images/story/201905/ball21.jpeg?EMXd5EiD_LhRjFKRbBGXvLH2ee41hcDm',
            },
            {
                id: 2,
                home_team: 'ERA Basketball Nymburk',
                visitor_team: 'BK JIP Pardubice',
                place: 'SC Nymburk',
                time: '18:00',
                description: 'Jedná se o mimořádný zápas mezi USK Praha a BC Spart. Potřebujeme uklízeče a 4 výčepní.',
                salary: 100,
                organizer: 'BC Sparta Praha',
                img: '/u183.png',
                freePosts: [
                    'Uklízeč',
                    'Výčepní',
                ],
                positions : {
                    available: ['uklízeč', 'zapisovatel'],
                    unavailable: ['časoměřič', '24 sekund'],
                },
                sport: 'basketball',
                image: 'http://mba.org.mt/wp-content/uploads/2015/12/basketball-wallpaper-1280x768-1180x768.jpg',
            }
        ],
    },
    {
        date: '14.10.2019',
        games: [
            {
                id: 3,
                home_team: 'ERA Basketball Nymburk',
                visitor_team: 'Basketball USK Praha',
                place: 'SC Nymburk',
                time: '12:00',
                description: 'Jedná se o mimořádný zápas mezi USK Praha a BC Spart. Potřebujeme uklízeče a 4 výčepní.',
                salary: 100,
                organizer: 'BC Sparta Praha',
                img: '/u183.png',
                freePosts: [
                    'Uklízeč',
                    'Výčepní',
                ],
                positions : {
                    available: ['uklízeč', 'zapisovatel'],
                    unavailable: ['časoměřič', '24 sekund'],
                },
                sport: 'basketball',
                image: 'http://mba.org.mt/wp-content/uploads/2015/12/basketball-wallpaper-1280x768-1180x768.jpg',
            },
            {
                id: 4,
                home_team: 'BC Sparta Praha',
                visitor_team: 'BK JIP Pardubice',
                place: 'Sportovní hala Folimanka',
                time: '16:00',
                date: '14.10.2019',
                description: 'Jedná se o mimořádný zápas mezi USK Praha a BC Spart. Potřebujeme uklízeče a 4 výčepní.',
                salary: 100,
                organizer: 'BC Sparta Praha',
                img: '/u183.png',
                freePosts: [
                    'Uklízeč',
                    'Výčepní',
                ],
                positions : {
                    available: ['uklízeč', 'zapisovatel'],
                    unavailable: ['časoměřič', '24 sekund'],
                },
                sport: 'basketball',
                image: 'http://mba.org.mt/wp-content/uploads/2015/12/basketball-wallpaper-1280x768-1180x768.jpg',
            }
        ],
    },
    {
        date: '15.10.2019',
        games: [
            {
                id: 5,
                home_team: 'BK JIP Pardubice',
                visitor_team: 'Basketball USK Praha',
                place: 'Hala Vodova, KP',
                time: '12:00',
                description: 'Jedná se o mimořádný zápas mezi USK Praha a BC Spart. Potřebujeme uklízeče a 4 výčepní.',
                salary: 100,
                organizer: 'BC Sparta Praha',
                img: '/u183.png',
                freePosts: [
                    'Uklízeč',
                    'Výčepní',
                ],
                positions : {
                    available: ['uklízeč', 'zapisovatel'],
                    unavailable: ['časoměřič', '24 sekund'],
                },
                sport: 'basketball',
                image: 'http://mba.org.mt/wp-content/uploads/2015/12/basketball-wallpaper-1280x768-1180x768.jpg',
            },
        ],
    },
    {
        date: '16.10.2019',
        games: [
            {
                id: 6,
                home_team: 'ERA Basketball Nymburk',
                visitor_team: 'BC Sparta Praha',
                place: 'SC Nymburk',
                time: '17:00',
                description: 'Jedná se o mimořádný zápas mezi USK Praha a BC Spart. Potřebujeme uklízeče a 4 výčepní.',
                salary: 100,
                organizer: 'BC Sparta Praha',
                img: '/u183.png',
                freePosts: [
                    'Uklízeč',
                    'Výčepní',
                ],
                positions : {
                    available: ['uklízeč', 'zapisovatel'],
                    unavailable: ['časoměřič', '24 sekund'],
                },
                sport: 'basketball',
                image: 'http://mba.org.mt/wp-content/uploads/2015/12/basketball-wallpaper-1280x768-1180x768.jpg',
            },
        ],
    },
    {
        date: '17.10.2019',
        games: [
            {
                id: 7,
                home_team: 'BC Sparta Praha',
                visitor_team: 'Basketball USK Praha',
                place: 'Sportovní hala Folimanka',
                time: '18:00',
                description: 'Jedná se o mimořádný zápas mezi USK Praha a BC Spart. Potřebujeme uklízeče a 4 výčepní.',
                salary: 100,
                organizer: 'BC Sparta Praha',
                img: '/u183.png',
                freePosts: [
                    'Uklízeč',
                    'Výčepní',
                ],
                positions : {
                    available: ['uklízeč', 'zapisovatel'],
                    unavailable: ['časoměřič', '24 sekund'],
                },
                sport: 'basketball',
                image: 'http://mba.org.mt/wp-content/uploads/2015/12/basketball-wallpaper-1280x768-1180x768.jpg',
            },
            {
                id: 8,
                home_team: 'BK JIP Pardubice',
                visitor_team: 'ERA Basketball Nymburk',
                place: 'Hala Vodova, KP',
                time: '19:00',
                date: '17.10.2019',
                description: 'Jedná se o mimořádný zápas mezi USK Praha a BC Spart. Potřebujeme uklízeče a 4 výčepní.',
                salary: 100,
                organizer: 'BC Sparta Praha',
                img: '/u183.png',
                freePosts: [
                    'Uklízeč',
                    'Výčepní',
                ],
                positions : {
                    available: ['uklízeč', 'zapisovatel'],
                    unavailable: ['časoměřič', '24 sekund'],
                },
                sport: 'basketball',
                image: 'http://mba.org.mt/wp-content/uploads/2015/12/basketball-wallpaper-1280x768-1180x768.jpg',
            },
        ],
    },
];
