export const previousUserGames = [
    {
        game: {
            id: 1,
            home_team: 'Basketball USK Praha',
            visitor_team: 'BC Sparta Praha',
            place: 'Pod juliskou 4',
            time: '10:30',
            date: '11.10.2018',
            description: 'Jedná se o mimořádný zápas mezi USK Praha a BC Spart. Potřebujeme uklízeče a 4 výčepní.',
            salary: 100,
            organizer: 'BC Sparta Praha',
            freePosts: [
                'Uklízeč',
                'Výčepní',
            ],
            sport: 'basketball',
            image: 'http://mba.org.mt/wp-content/uploads/2015/12/basketball-wallpaper-1280x768-1180x768.jpg',
        },
        rating: -2,
        position: 'Uklízeč',
        comment: '',
    },
    {
        game: {
            id: 9,
            home_team: 'Sparta Praha',
            visitor_team: 'SK Slavia Praha',
            place: 'Stadion Letná',
            time: '18:00',
            date: '9.10.2018',
            salary: 200,
            freePosts: [
                'Uklízeč',
                'Výčepní',
            ],
            sport: 'football',
            image: 'https://akm-img-a-in.tosshub.com/indiatoday/images/story/201905/ball21.jpeg?EMXd5EiD_LhRjFKRbBGXvLH2ee41hcDm',
        },
        rating: 4.5,
        position: 'Uklízeč',
        comment: 'Super práce, jako vždy.',
    },
    {
        game: {
            id: 2,
            home_team: 'ERA Basketball Nymburk',
            visitor_team: 'BK JIP Pardubice',
            place: 'SC Nymburk',
            time: '18:00',
            date: '11.10.2018',
            description: 'Jedná se o mimořádný zápas mezi USK Praha a BC Spart. Potřebujeme uklízeče a 4 výčepní.',
            salary: 100,
            organizer: 'BC Sparta Praha',
            freePosts: [
                'Uklízeč',
                'Výčepní',
            ],
            sport: 'basketball',
            image: 'http://mba.org.mt/wp-content/uploads/2015/12/basketball-wallpaper-1280x768-1180x768.jpg',
        },
        rating: -1,
        position: 'Uklízeč',
        comment: '',
    }
];
